on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  # --------------------------------------------------------------------------------------------------------------------
  build:
    runs-on: ubuntu-latest
    env:
      STARBURST_LICENSE: ${{ secrets.STARBURST_TEST_LICENSE }}
    steps:
    - uses: actions/checkout@v2
    - name: Set up python 3.11
      uses: actions/setup-python@v2
      with:
        python-version: 3.11
    - name: 'Install build dependencies'
      run: |
        python -m pip install --upgrade pip
        python -m pip install -r requirements.txt
    - name: 'Run SEP data product tests'
      run: | 
        echo $STARBURST_LICENSE > tests/docker/starburstdata.license
        ./test-sep-dp.sh
    
